version: "3.9"
services:
  db:
    build:
      context: ad_mysql
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  app:
    build:
      context: app
    environment:
      S3_BUCKET: "test_bucket"
      S3_ACCESS_KEY: "root"
      S3_SECRET_KEY: "password"
      S3_ENDPOINT: "http://s3-test:9000"
      MYSQL_HOST: "db"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "analytics"
      METAFLOW_RUN_ADVERTISERIDS: "1,3"
      USER: kristijan
    depends_on: [db]

  s3-test:
    image: minio/minio
    environment:
     MINIO_ROOT_USER: root
     MINIO_ROOT_PASSWORD: password
    entrypoint: ["sh","-c"]
    command: ["mkdir -p /test/test_bucket && /usr/bin/docker-entrypoint.sh minio server --console-address :9001 /test"]
    ports:
      - "9000:9000"
      - "9001:9001"